export const UPDATE_CURRENT_HEALTH = "UPDATE_CURRENT_HEALTH";
export const UPDATE_TEMP_HEALTH="UPDATE_TEMP_HEALTH";
export const UPDATE_CLASS_CURRENT_HIT_DICE="UPDATE_CLASS_CURRENT_HIT_DICE";
export const UPDATE_TRAIT="UPDATE_TRAIT";