name: 'Label Actions'
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v4
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          config-path: '.github/label-actions.yml'
          process-only: 'issues'

